version: '3.8'

services:
  web:
    build: ./ussc
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ussc/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=list

volumes:
  postgres_volume:

